"use client";

import { useEffect, useState } from "react";
import { SiteFooter, SiteHeader } from "./components/SiteChrome";

const A="https://arizonacommercialinspections.com/wp-content/uploads/";
const services=["ADA ACCESSIBILITY INSPECTIONS","COMMERCIAL BUILDING INSPECTIONS","INDUSTRIAL BUILDING INSPECTIONS","MULTI-FAMILY PROPERTY INSPECTIONS","LEASING INSPECTIONS","ELEVATOR/ESCALATOR INSPECTION","CHURCH INSPECTIONS","SEWER CAMERA INSPECTIONS","TERMITE INSPECTIONS","POOL AND SPA INSPECTIONS","FIRE AND LIFE SAFETY INSPECTION","RETAIL PROPERTY INSPECTIONS","COMMERCIAL BUILDING REVIEW (CUSTOMIZED TO THE SPECIFIC TYPE OF BUILDING)","NATIONAL STANDARDS FOR THE PHYSICAL INSPECTION OF REAL ESTATE (NSPIRE) INSPECTIONS"];
const gallery=["2021/05/AZCPIimg-400x284.jpg","2021/05/AZCPIimg3-400x284.jpg","2021/05/AZCPIimg4-400x284.jpg","2021/05/image0-400x284.jpeg","2021/05/AZCPI2-400x284.jpg","2021/05/AZCPIimg2-400x284.jpg","2021/05/Untitled-1-400x284.jpg","2024/02/Warehouse-400x284.jpg","2024/02/Storage-facilities-400x284.jpg","2024/02/School-2-400x284.jpg","2024/02/School-1-400x284.jpg","2024/02/Restaurant-400x284.jpg","2024/02/Reatail-400x284.jpg","2024/02/IMG_4528-400x284.jpg","2024/02/Country-club-infrastructure-400x284.jpg","2024/02/Advanced-HVAc-400x284.jpg"];

export default function Home(){
  const [lightbox,setLightbox]=useState<number|null>(null);
  useEffect(()=>{const close=(event:KeyboardEvent)=>{if(event.key==="Escape")setLightbox(null)};window.addEventListener("keydown",close);return()=>window.removeEventListener("keydown",close)},[]);
  return <>
  <SiteHeader active="home"/>
  <main>
    <section className="hero"><div className="heroCard"><h1>ARIZONA</h1><h2>COMMERCIAL PROPERTY INSPECTIONS</h2><p>ARIZONA’S #1 COMMERCIAL INSPECTION COMPANY</p></div><div className="heroButtons"><a href="tel:1-480-808-1170">(480) 808-1170</a><a href="/schedule-an-inspection/">Schedule Now!</a></div></section>
    <section className="intro"><h2>SPECIALIZING IN COMMERCIAL PROPERTY INSPECTIONS IN ARIZONA</h2><p>Welcome to Arizona Commercial Property Inspections. We are a team of professionally certified and highly qualified commercial property<br className="desktop"/> inspectors who have years of experience, and the highest qualifications in the industry.</p></section>
    <section className="aboutWrap" id="about"><div className="about"><img src={A+"2021/05/AZCPI2.jpg"} alt="Phoenix Commercial Building Inspection"/><div className="aboutCopy"><span>YOUR ONE-STOP-SHOP FOR</span><h2>COMMERCIAL<br/>BUILDING INSPECTORS</h2><h4>CCPIA CERTIFIED COMMERCIAL BUILDING INSPECTORS</h4><p>Welcome to Arizona Commercial Property Inspections – the leaders in the commercial building inspection industry. We have years of experience, and we are fully certified through <em>CCPIA</em> (Certified Commercial Property Inspection Association) and <em>NACBI</em> (National Association of Certified Building Inspectors).</p><p>We provide a high level of customer service, thorough commercial building assessments, and a detailed inspection report delivered to you within 24 hours of your on-site inspection.</p><p>Whether you are buying, selling, or currently own a commercial building, we are here to provide you with accurate information about the true condition of your property.</p><a className="blackButton" href="/about-us/">ABOUT US</a></div></div></section>
    <section className="properties"><div className="container"><h2>PROPERTIES WE INSPECT</h2><p>We provide our clients with professional, thorough, and highly detailed commercial property inspections.<br/>Whether you are buying a property, getting ready to sell one, or just want to know the condition of your<br className="desktop"/> current property – we provide the best inspections, and industry-leading reports for properties of every<br className="desktop"/> type, size, and location.</p><div className="cards"><Property cls="one" title="INVESTMENT PROPERTIES">MULTI-FAMILY PROPERTIES, APARTMENT BUILDINGS, RENTAL FACILITIES, LEASED SPACES, DOCTOR/DENTAL OFFICES, CONDOMINIUMS, & MORE</Property><Property cls="two" title="HOSPITALITY PROPERTIES">HOTELS, MOTELS, RESTAURANTS, CAFES, INDOOR & OUTDOOR MALLS, LODGING FACILITIES, SMALL STORES, BANQUET HALLS, & MORE</Property><Property cls="three" title="COMMERCIAL & LIGHT INDUSTRIAL">WAREHOUSES, MANUFACTURING FACILITIES, PARKING GARAGES, LARGE OFFICE FACILITIES, MULTI-BUILDING PROPERTIES, & MORE</Property></div></div></section>
    <section className="gallery" id="gallery"><h2>EXAMPLES OF PROPERTIES WE INSPECT</h2><div className="galleryGrid">{gallery.map((x,i)=><button key={x} type="button" onClick={()=>setLightbox(i)} aria-label={`Enlarge property inspection photo ${i+1}`}><img src={A+x} alt={`Arizona commercial property inspection ${i+1}`}/><span>＋</span></button>)}</div></section>
    {lightbox!==null&&<div className="lightbox" role="dialog" aria-modal="true" aria-label="Enlarged property photo" onClick={()=>setLightbox(null)}><button className="lightboxClose" type="button" onClick={()=>setLightbox(null)} aria-label="Close enlarged photo">×</button><button className="lightboxArrow previous" type="button" onClick={e=>{e.stopPropagation();setLightbox((lightbox-1+gallery.length)%gallery.length)}} aria-label="Previous photo">‹</button><img onClick={e=>e.stopPropagation()} src={A+gallery[lightbox].replace("-400x284","")} alt={`Enlarged Arizona commercial property inspection ${lightbox+1}`}/><button className="lightboxArrow next" type="button" onClick={e=>{e.stopPropagation();setLightbox((lightbox+1)%gallery.length)}} aria-label="Next photo">›</button></div>}
    <section className="serviceSection"><div className="serviceLayout"><div className="serviceCopy"><h2>OUR SERVICES</h2><div className="serviceGrid">{services.map(x=><div key={x}><b>✓</b><span>{x}</span></div>)}</div><a className="blackButton" href="/schedule-an-inspection/">Schedule Now!</a></div><div className="serviceVisual"><div className="serviceRed"/><div className="serviceDark"/><img src={A+"2021/05/AZCPI2.jpg"} alt="Commercial building inspected by Arizona Commercial Property Inspections"/></div></div></section>
    <section className="areas"><div className="areasCopy"><h2>PHOENIX COMMERCIAL INSPECTIONS<br/>& ALL OF ARIZONA</h2><p>Providing commercial property inspection services in the <a href="/">Phoenix Metro Area</a> as well as <a href="/about-us/">Tucson</a>, <a href="/inspection-services/">Flagstaff</a>, <a href="/property-condition-assessments/">Prescott</a>, <a href="/showlow-az-commercial-building-inspections/">Showlow</a>, <a href="/kingman-arizona-commercial-building-inspections/">Kingman</a>, <a href="/yuma-az-commercial-inspections/">Yuma</a>, <a href="/payson-az-commercial-building-inspections/">Payson</a>, and <a href="/lake-havasu-arizona-commercial-building-inspections/">Lake Havasu</a>. If you need a commercial property inspection anywhere in Arizona, give us a call: <strong>(480) 808-1170</strong></p><div className="mapWrap"><iframe title="Arizona Commercial Property Inspections service area map" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1667542.3276277494!2d-112.96346224375!3d35.283149825751536!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x872b67348d22958d%3A0x8c20d1d807fa8b98!2sArizona%20Commercial%20Property%20Inspections!5e0!3m2!1sen!2sus!4v1786573127143!5m2!1sen!2sus" loading="lazy" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen/></div></div></section>
  </main>
  <SiteFooter/>
</>}
function Property({cls,title,children}:{cls:string,title:string,children:React.ReactNode}){return <article className={`propertyItem ${cls}`}><a className="propertyCard" href="/inspection-services/"><div><h3>{title}</h3><p>{children}</p></div></a><a className="propertyArrow" href="/inspection-services/" aria-label={`View ${title.toLowerCase()} inspection services`}>→</a></article>}
