const A="https://arizonacommercialinspections.com/wp-content/uploads/";
const services=["ADA ACCESSIBILITY INSPECTIONS","COMMERCIAL BUILDING INSPECTIONS","INDUSTRIAL BUILDING INSPECTIONS","MULTI-FAMILY PROPERTY INSPECTIONS","LEASING INSPECTIONS","ELEVATOR/ESCALATOR INSPECTION","CHURCH INSPECTIONS","SEWER CAMERA INSPECTIONS","TERMITE INSPECTIONS","POOL AND SPA INSPECTIONS","FIRE AND LIFE SAFETY INSPECTION","RETAIL PROPERTY INSPECTIONS","COMMERCIAL BUILDING REVIEW (CUSTOMIZED TO THE SPECIFIC TYPE OF BUILDING)","NATIONAL STANDARDS FOR THE PHYSICAL INSPECTION OF REAL ESTATE (NSPIRE) INSPECTIONS"];
const gallery=["2021/05/AZCPIimg-400x284.jpg","2021/05/AZCPIimg3-400x284.jpg","2021/05/AZCPIimg4-400x284.jpg","2021/05/image0-400x284.jpeg","2021/05/AZCPI2-400x284.jpg","2021/05/AZCPIimg2-400x284.jpg","2021/05/Untitled-1-400x284.jpg","2024/02/Warehouse-400x284.jpg","2024/02/Storage-facilities-400x284.jpg","2024/02/School-2-400x284.jpg","2024/02/School-1-400x284.jpg","2024/02/Restaurant-400x284.jpg","2024/02/Reatail-400x284.jpg","2024/02/IMG_4528-400x284.jpg","2024/02/Country-club-infrastructure-400x284.jpg","2024/02/Advanced-HVAc-400x284.jpg"];

export default function Home(){return <>
  <header className="siteHeader">
    <div className="contactBar"><span className="contactItem"><i>▯</i>(480) 808-1170</span><span className="contactItem"><i>✉</i>arizonacpi@gmail.com</span></div>
    <div className="navBar"><a href="/" className="brand"><img src="/ArizonaCommercialPropertyInspections-logo.webp" alt="Phoenix Arizona Commercial Building Inspections"/></a><nav><a className="active" href="/">HOME</a><a href="/about-us/">ABOUT</a><a href="/inspection-services/">SERVICES⌄</a><a href="#gallery">BLOG</a><a href="#contact">CONTACT</a></nav><a className="request" href="/schedule-an-inspection/">REQUEST INSPECTION <b>□</b></a><span className="menu">☰</span></div>
  </header>
  <main>
    <section className="hero"><div className="heroCard"><h1>ARIZONA</h1><h2>COMMERCIAL PROPERTY INSPECTIONS</h2><p>ARIZONA’S #1 COMMERCIAL INSPECTION COMPANY</p></div><div className="heroButtons"><a href="tel:1-480-808-1170">(480) 808-1170</a><a href="/schedule-an-inspection/">Schedule Now!</a></div></section>
    <section className="intro"><h2>SPECIALIZING IN COMMERCIAL PROPERTY INSPECTIONS IN ARIZONA</h2><p>Welcome to Arizona Commercial Property Inspections. We are a team of professionally certified and highly qualified commercial property<br className="desktop"/> inspectors who have years of experience, and the highest qualifications in the industry.</p></section>
    <section className="aboutWrap" id="about"><div className="about"><img src={A+"2021/05/AZCPI2.jpg"} alt="Phoenix Commercial Building Inspection"/><div className="aboutCopy"><span>YOUR ONE-STOP-SHOP FOR</span><h2>COMMERCIAL<br/>BUILDING INSPECTORS</h2><h4>CCPIA CERTIFIED COMMERCIAL BUILDING INSPECTORS</h4><p>Welcome to Arizona Commercial Property Inspections – the leaders in the commercial building inspection industry. We have years of experience, and we are fully certified through <em>CCPIA</em> (Certified Commercial Property Inspection Association) and <em>NACBI</em> (National Association of Certified Building Inspectors).</p><p>We provide a high level of customer service, thorough commercial building assessments, and a detailed inspection report delivered to you within 24 hours of your on-site inspection.</p><p>Whether you are buying, selling, or currently own a commercial building, we are here to provide you with accurate information about the true condition of your property.</p><a className="blackButton" href="/about-us/">ABOUT US</a></div></div></section>
    <section className="properties"><div className="container"><h2>PROPERTIES WE INSPECT</h2><p>We provide our clients with professional, thorough, and highly detailed commercial property inspections.<br/>Whether you are buying a property, getting ready to sell one, or just want to know the condition of your<br className="desktop"/> current property – we provide the best inspections, and industry-leading reports for properties of every<br className="desktop"/> type, size, and location.</p><div className="cards"><Property cls="one" title="INVESTMENT PROPERTIES">MULTI-FAMILY PROPERTIES, APARTMENT BUILDINGS, RENTAL FACILITIES, LEASED SPACES, DOCTOR/DENTAL OFFICES, CONDOMINIUMS, & MORE</Property><Property cls="two" title="HOSPITALITY PROPERTIES">HOTELS, MOTELS, RESTAURANTS, CAFES, INDOOR & OUTDOOR MALLS, LODGING FACILITIES, SMALL STORES, BANQUET HALLS, & MORE</Property><Property cls="three" title="COMMERCIAL & LIGHT INDUSTRIAL">WAREHOUSES, MANUFACTURING FACILITIES, PARKING GARAGES, LARGE OFFICE FACILITIES, MULTI-BUILDING PROPERTIES, & MORE</Property></div></div></section>
    <section className="gallery" id="gallery"><h2>EXAMPLES OF PROPERTIES WE INSPECT</h2><div className="galleryGrid">{gallery.map((x,i)=><a key={x} href={A+x.replace("-400x284","")}><img src={A+x} alt={`Arizona commercial property inspection ${i+1}`}/><span>＋</span></a>)}</div></section>
    <section className="serviceSection"><div className="container"><h2>OUR SERVICES</h2><div className="serviceGrid">{services.map(x=><div key={x}><b>✓</b>{x}</div>)}</div><a className="blackButton" href="/schedule-an-inspection/">Schedule Now!</a></div></section>
    <section className="areas"><div className="areasCopy"><h2>PHOENIX COMMERCIAL<br/>INSPECTIONS & ALL OF ARIZONA</h2><p>Providing commercial property inspection services in the <a href="/">Phoenix Metro Area</a> as well as <a href="/about-us/">Tucson</a>, <a href="/inspection-services/">Flagstaff</a>, <a href="/property-condition-assessments/">Prescott</a>, Showlow, Kingman, Yuma, Payson, and Lake Havasu.</p><p>If you need a commercial property inspection anywhere in Arizona, give us a call: <strong>(480) 808-1170</strong></p></div><img src={A+"2021/05/AZCPI2.jpg"} alt="Home Inspector"/></section>
  </main>
  <footer id="contact"><div className="footerTop"><div><i>▯</i><h4>CALL US</h4><p>(480) 808-1170</p></div><div><i>✉</i><h4>EMAIL US</h4><p><a href="mailto:arizonacpi@gmail.com">Click Here to Email</a></p></div><div><i>□</i><h4>REQUEST INSPECTION</h4><p><a href="/schedule-an-inspection/">Click Here to Request</a></p></div></div><p className="legal"><a href="/privacy-policy/">Privacy Policy</a> | <a href="/terms-of-service/">Terms of Service</a></p><div className="social">G　◎　f　▶</div><p className="credit">Designed By Full View Home Inspection Website Design</p></footer>
</>}
function Property({cls,title,children}:{cls:string,title:string,children:React.ReactNode}){return <article className={`propertyCard ${cls}`}><div><h3>{title}</h3><p>{children}</p><a href="/inspection-services/">$</a></div></article>}
