const services = ["ADA Accessibility Inspections","Commercial Building Inspections","Industrial Building Inspections","Multi-Family Property Inspections","Leasing Inspections","Elevator/Escalator Inspection","Church Inspections","Sewer Camera Inspections","Termite Inspections","Pool and Spa Inspections","Fire and Life Safety Inspection","Retail Property Inspections","Commercial Building Review","NSPIRE Inspections"];
const properties = [
  ["Investment Properties","Multi-family properties, apartment buildings, rental facilities, leased spaces, doctor/dental offices, condominiums, & more"],
  ["Hospitality Properties","Hotels, motels, restaurants, cafes, indoor & outdoor malls, lodging facilities, small stores, banquet halls, & more"],
  ["Commercial & Light Industrial","Warehouses, manufacturing facilities, parking garages, large office facilities, multi-building properties, & more"],
];
const gallery = ["AZCPIimg.jpg","AZCPIimg3.jpg","AZCPIimg4.jpg","image0.jpeg","AZCPI2.jpg","AZCPIimg2.jpg","Warehouse.jpg","Storage-facilities.jpg","School-2.jpg","Restaurant.jpg","Reatail.jpg","Advanced-HVAc.jpg"];

export default function Home() {
  return <>
    <header className="topbar"><div><span>☎</span> (480) 808-1170</div><div><span>✉</span> arizonacpi@gmail.com</div></header>
    <nav className="nav"><a className="logo" href="/"><b>ARIZONA</b><small>COMMERCIAL PROPERTY<br/>INSPECTIONS</small></a><div className="links"><a href="#about">ABOUT US</a><a href="#services">INSPECTION SERVICES</a><a href="#areas">SERVICE AREAS</a><a href="#contact">CONTACT US</a></div><a className="button small" href="/schedule-an-inspection/">REQUEST INSPECTION</a></nav>
    <main>
      <section className="hero"><div className="heroInner"><p className="eyebrow">ARIZONA’S #1 COMMERCIAL INSPECTION COMPANY</p><h1>ARIZONA</h1><h2>COMMERCIAL PROPERTY<br/>INSPECTIONS</h2><div className="actions"><a className="button light" href="tel:1-480-808-1170">(480) 808-1170</a><a className="button" href="/schedule-an-inspection/">SCHEDULE NOW!</a></div></div></section>
      <section className="intro section"><h2>SPECIALIZING IN COMMERCIAL PROPERTY INSPECTIONS IN ARIZONA</h2><p>Welcome to Arizona Commercial Property Inspections. We are a team of professionally certified and highly qualified commercial property inspectors who have years of experience, and the highest qualifications in the industry.</p></section>
      <section id="about" className="split"><div className="buildingPhoto"/><div className="copy"><p className="eyebrow gold">YOUR ONE-STOP-SHOP FOR</p><h2>COMMERCIAL BUILDING INSPECTORS</h2><h4>CCPIA CERTIFIED COMMERCIAL BUILDING INSPECTORS</h4><p>Welcome to Arizona Commercial Property Inspections – the leaders in the commercial building inspection industry. We have years of experience, and we are fully certified through CCPIA and NACBI.</p><p>We provide a high level of customer service, thorough commercial building assessments, and a detailed inspection report delivered to you within 24 hours of your on-site inspection.</p><p>Whether you are buying, selling, or currently own a commercial building, we are here to provide you with accurate information about the true condition of your property.</p><a className="button" href="/about-us/">ABOUT US</a></div></section>
      <section className="section properties"><h2>PROPERTIES WE INSPECT</h2><p>We provide our clients with professional, thorough, and highly detailed commercial property inspections. Whether you are buying a property, getting ready to sell one, or want to know the condition of your current property – we provide industry-leading reports for properties of every type, size, and location.</p><div className="cards">{properties.map(([t,d],i)=><article key={t} className={`card card${i+1}`}><div><h3>{t}</h3><p>{d}</p><a href="/inspection-services/">→</a></div></article>)}</div></section>
      <section className="section gallery"><h2>EXAMPLES OF PROPERTIES WE INSPECT</h2><div className="galleryGrid">{gallery.map((f)=><img key={f} src={`https://arizonacommercialinspections.com/wp-content/uploads/${["Warehouse.jpg","Storage-facilities.jpg","School-2.jpg","Restaurant.jpg","Reatail.jpg","Advanced-HVAc.jpg"].includes(f)?"2024/02":"2021/05"}/${f}`} alt="Arizona commercial property inspection"/>)}</div></section>
      <section id="services" className="services"><div className="section"><h2>OUR SERVICES</h2><div className="serviceGrid">{services.map(s=><div key={s}><span>✓</span>{s}</div>)}</div><a className="button light" href="/schedule-an-inspection/">SCHEDULE NOW!</a></div></section>
      <section id="areas" className="split reverse"><div className="inspectorPhoto"/><div className="copy"><h2>PHOENIX COMMERCIAL INSPECTIONS & ALL OF ARIZONA</h2><p>Providing commercial property inspection services in the Phoenix Metro Area as well as Tucson, Flagstaff, Prescott, Show Low, Kingman, Yuma, Payson, and Lake Havasu.</p><p>If you need a commercial property inspection anywhere in Arizona, give us a call:</p><a className="phone" href="tel:1-480-808-1170">(480) 808-1170</a></div></section>
    </main>
    <footer id="contact"><div><b>CALL US</b><a href="tel:1-480-808-1170">(480) 808-1170</a></div><div><b>EMAIL US</b><a href="mailto:arizonacpi@gmail.com">Click Here to Email</a></div><div><b>REQUEST INSPECTION</b><a href="/schedule-an-inspection/">Click Here to Request</a></div><p>© Arizona Commercial Property Inspections · <a href="/privacy-policy/">Privacy Policy</a> · <a href="/terms-of-service/">Terms of Service</a></p></footer>
  </>;
}
