import type { Metadata } from "next";
import { SiteFooter, SiteHeader } from "../components/SiteChrome";
import { InspectionAccordion } from "./InspectionAccordion";

const A="/uploads/";
const coreServices=[
  ["Property Condition Inspections","Comprehensive assessments of the overall condition of a commercial property, including its structural elements, systems, and components. Inspection professionals conduct a thorough examination, utilizing a checklist that covers foundations, roofing, HVAC systems, plumbing, electrical, and other critical components. They identify any existing issues or potential concerns that might affect the property’s value or safety. The inspection may involve visual examinations, testing, and documentation of findings."],
  ["Property Condition Assessments","A detailed review of a property's current condition for buyers, owners, lenders, and investors."],
  ["Limited Scope Inspections","Targeted inspections customized to the systems or areas most important to your transaction."],
  ["Yearly Maintenance Inspections","Recurring evaluations that help owners plan maintenance and protect their investment."],
  ["Draw Inspections","Independent construction-progress observations completed at key draw milestones."],
  ["Insurance Loss Inspections","Clear documentation of building conditions following a covered loss."],
  ["Insurance Pre-loss Inspections","Pre-loss documentation that records a property's condition before an incident occurs."],
  ["MEP Inspections (Mechanical, Electrical, Plumbing)","Focused evaluation of a building's essential mechanical, electrical, and plumbing systems."],
  ["Triple-Net Lease Inspections","Practical condition information for landlords and tenants entering or renewing a triple-net lease."],
  ["Construction Quality Control","Independent observations that help identify workmanship and installation concerns."],
  ["Thermal Imaging Scans and Inspection","Infrared scanning used to help identify hidden moisture, heat loss, and electrical anomalies."]
];
const additional=[
  ["Opinion of Cost Report","An “Opinion of Cost” report provides a comprehensive overview of potential costs associated with identified issues or recommended improvements. This report goes beyond highlighting the inspection findings by estimating the financial implications of addressing specific concerns. It outlines projected costs for repairs, maintenance, or upgrades, aiding owners and stakeholders in planning and prioritizing necessary actions."],
  ["Capitol Reserve Study","Long-term forecasting for major repairs, replacements, and reserve funding."],
  ["Phase 1, 2, and 3 Environmental Assessments","Environmental due-diligence services coordinated to match the property and transaction."],
  ["NFPA-70B Annual Electrical Equipment Maintenance Inspections","Annual electrical equipment maintenance inspections aligned with NFPA guidance."],
  ["Thermal Imaging","Infrared scanning that can reveal patterns not visible during a standard visual inspection."],
  ["Advanced HVAC Inspection","A deeper technical evaluation of commercial heating, ventilation, and cooling systems."],
  ["Termite Inspection","Inspection for evidence of wood-destroying organisms and related damage."],
  ["Sewer Camera Inspection","A camera assessment of sewer lines to identify blockages, damage, leaks, or other potential problems before they become expensive repairs."],
  ["Fire and Life Safety Inspections","Review of visible fire and life-safety features and conditions."],
  ["Fire Suppression System Inspection","Specialist evaluation of fire-suppression systems and components."],
  ["Kitchen Hood Inspection","Inspection of commercial kitchen exhaust and hood systems."],
  ["Commercial Kitchen Inspection","Review of visible commercial kitchen systems, equipment, and safety concerns."],
  ["ADA Inspection","Accessibility observations to help identify barriers and areas of concern."],
  ["Air Quality Inspection","Testing and assessment options for indoor air-quality concerns."],
  ["Moisture Intrusion Inspection","Focused investigation of active or suspected moisture intrusion."]
];

export const metadata:Metadata={title:"Commercial Inspection Services | Arizona Commercial Property Inspections",description:"Commercial property inspections, assessments, specialty inspections, and inspection reports throughout Arizona."};

export default function InspectionServices(){return <>
  <SiteHeader active="services"/>
  <main className="inspectionPage">
    <section className="inspectionHero"><img src={A+"2021/04/architecture-1448221_1920.jpg"} alt="Commercial architecture"/><div><h1>OUR INSPECTIONS</h1></div></section>
    <section className="inspectionIntro"><h2>INSPECTING PROPERTIES OF EVERY SIZE &amp; TYPE</h2><p>Our inspectors help the client understand the true condition of the property. After providing an educational in-person or virtual review of our findings, we complete and deliver our report within 24 hours.</p><a className="blackButton" href="/schedule-an-inspection/">Book Now!</a></section>
    <section className="commercialOverview"><div className="overviewImages"><img src={A+"2021/05/Untitled-1.jpg"} alt="Commercial property inspection"/><img src={A+"2021/05/AZCPIimg4.jpg"} alt="Flagstaff commercial property inspection"/></div><div className="overviewCopy"><h2>OUR COMMERCIAL<br/>INSPECTIONS</h2><p>We provide thorough commercial property inspections for many different types of buildings – including:</p><ul><li>Manufacturing facilities</li><li>Medical and Dental offices</li><li>Warehouses</li><li>Churches</li><li>Office Buildings</li><li>Office Suite Condominiums</li><li>Apartments buildings and complexes</li><li>Lodging and hotels</li><li>Strip malls</li></ul><p>Each property is unique – so we tailor our inspections to meet the needs of our individual clients and their properties. After your inspection is complete, we provide you with an industry-leading inspection report that covers all of our findings in an easy-to-read format. When you choose us – you are getting the best inspection in Arizona!</p><a className="blackButton" href="tel:1-480-808-1170">(480) 808-1170</a></div></section>
    <section className="inspectionServices"><h2>OUR INSPECTION SERVICES</h2><InspectionAccordion services={coreServices}/></section>
    <section className="virtualReview"><h2>VIRTUAL REVIEW</h2><p>Here at AZCPI, we prioritize an educational walk through of our findings after completion of the inspection. With the reality that many of our clients are from out of state, we provide a virtual walkthrough experience for any client that will be unable to attend in-person.</p></section>
    <section className="standardAssessment"><div className="assessmentCopy"><h2>STANDARD PROPERTY CONDITION ASSESSMENT INSPECTIONS</h2><p>This form of inspection is performed by our highly experienced inspectors who have actual commercial trade experience. The goal of this inspection is to find and report on any defects, maintenance/repair needs, or safety concerns.</p><p>The duration for this kind of inspection can be anywhere from a half-day, to 5 full days depending on the property size and complexity. The report will be generated within 24 hours of inspection completion.</p><p>An in-person or virtual walk-through is recommended on the day of inspection completion. This walk-through will include all involved inspectors educating client(s) on their findings and making recommendations for repair/correction needs.</p><p>These inspections can also be scheduled annually to determine continuing property condition, maintenance, and repair needs.</p><a className="blackButton" href="tel:1-480-808-1170">(480) 808-1170</a></div><div className="assessmentList"><h3>A STANDARD COMMERCIAL PROPERTY<br/>INSPECTION INCLUDES:</h3><p>(Any of these can be added or subtracted from the inspection and agreed upon prior to the inspection for a customized price/view).</p><ul><li>Document Review</li><li>Site Utilities, Drainage, and Paving</li><li>Frame, Structure, and Building Envelope</li><li>Roof Covering and Structure</li><li>Mechanical and Electrical Systems</li><li>Plumbing Systems</li><li>Heating, Ventilation, and Air Conditioning</li><li>Life Safety/Fire Protection</li><li>Interior Elements and Finishes</li><li>Exterior Elements and Finishes</li><li>Kitchen and Cooking Equipment</li><li>Repair and Correction Recommendations</li></ul><a href="https://ccpia.org/standards-of-practice/">(SEE CCPIA STANDARDS OF PRACTICE)</a></div></section>
    <section className="additionalWrap"><div className="additionalServices"><h2>ADDITIONAL INSPECTION SERVICES:</h2><p>The following ancillary inspections can be added to any commercial property inspection for a customized view of the property and its additional systems.</p><div className="additionalGrid"><div>{additional.slice(0,7).map(([title,copy],i)=><details key={title} open={i===0}><summary>{title}</summary><p>{copy}</p></details>)}</div><div>{additional.slice(7).map(([title,copy],i)=><details key={title} open={i===0}><summary>{title}</summary><p>{copy}</p></details>)}</div></div></div></section>
    <section className="teamSection"><div className="teamCopy"><h2>T.E.A.M. INSPECTIONS</h2><p>The TEAM approach (Technical Experts And Management) is needed whenever a client desires a more technically detailed inspection.</p><p>In such cases, a team of licensed contractors is hired to inspect and include costs of currently needed repairs and maintenance. 5-year projected maintenance costs and potential warranties or certifications (such as fire sprinkler or elevator certifications) may also be provided by such specialists.</p><p>Arizona Commercial Property Inspections can manage any level of detailed inspection your company desires. Yearly Property Condition Assessments are recommended after the initial inspection to monitor your building’s performance, maintenance and it’s unique needs.</p><p>Hiring AZCPI for your annual inspections would be beneficial in many ways, especially because of the relationship between the client, property managers, and the inspectors that will be created during the initial inspection.</p><a className="blackButton" href="tel:1-480-808-1170">(480) 808-1170</a></div><div className="professionalList"><h3>EXAMPLE OF SUPPLEMENTED PROFESSIONALS<br/>MAY INCLUDE:</h3>{["Structural engineers","Environmental Specialists (Mold, Lead, Asbestos, Radon, Etc.)","Elevator Specialists","Pest Control Experts","HVAC (Heating, Ventilation, Air Conditioning) Specialists","Roofing Contractors","Electrical Contractors","Asphalt and Paving Specialists","Plumbing Contractors","Window & Door Contractors","Fire Protection Specialists"].map(x=><p key={x}>– {x}</p>)}</div></section>
    <section className="reportsWrap"><div className="reportsSection"><img src={A+"2021/05/Home-Inspection-Software2-e1572267234321.png"} alt="Digital commercial inspection report on desktop and mobile"/><span>Thorough &amp; Comprehensive</span><h2>OUR INSPECTION REPORTS</h2><p>Within 24 hours of inspection completion, AZCPI will electronically deliver a report published into industry-leading software. These reports are designed for the ease of use of the client.</p></div></section>
    <section className="serviceAreaStrip"><h2>FLAGSTAFF COMMERCIAL<br/>INSPECTIONS &amp; ALL OF ARIZONA</h2><p>Providing commercial property inspection services in the <a href="/">Phoenix Metro Area</a> as well as <a href="/about-us/">Tucson</a>, <a href="/inspection-services/">Flagstaff</a>, <a href="/property-condition-assessments/">Prescott</a>, Showlow, Kingman, Yuma, Payson, and Lake Havasu. If you need a commercial property inspection anywhere in Arizona, give us a call.</p></section>
  </main>
  <SiteFooter/>
</>}
